In [ ]:
!pip install tensorflow
!pip install tensorflow-gpu

In [ ]:
## loading the data
import tensorflow as tf
import tensorflow.keras

(x_train, y_train), (x_test, y_test)= tf.keras.datasets.mnist.load_data()
x_train = x_train.reshape(len(y_train), 784)
x_test = x_test.reshape(len(y_test), 784)
print("x_train", x_train)
print("y_train", y_train)
print("x_test", x_test)
print("y_test", y_test)



x_train [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y_train [5 0 4 ... 5 6 8]
x_test [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y_test [7 2 1 ... 4 5 6]


In [ ]:
import numpy as np
## mean centering and normalization:
mean_vals = np.mean(x_train, axis=0)
std_val = np.std(x_train)
print(mean_vals)
print(std_val)

[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 2.10000000e-03 7.83333333e-03 3.60000000e-03 1.50000000e-04
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 2.66666667e-04 9.16666667e-04 9.28333333e-03 2.42833333e-02
 4.37166667e-02 6.41000000e-02 1.20133333e-01 1.60733333e-01
 1.74183333e-01 1.77433333e-01 1.89316667e-01 1.74150000e-01
 1.86933333e-01 1.53650000e-01 1.00116667e-01 7.12333333e-02
 5.38166667e-02 2.13666667e-02 1.00833333e-02 3.53333333e-03
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 1.06666667e-03 7.00000000e-04
 6.95000000e-03 5.48333333e-03 4.71000000e-02 1.38400000e-01
 2.64183333e-01 5.066166

In [ ]:
X_train_centered = (x_train - mean_vals)/std_val
X_test_centered = (x_test - mean_vals)/std_val
print("X_train_centered", X_train_centered)
print("X_test_centered",X_test_centered)
del x_train, x_test

X_train_centered [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
X_test_centered [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
print(X_train_centered.shape, y_train.shape)
print(X_test_centered.shape, y_test.shape)

(60000, 784) (60000,)
(10000, 784) (10000,)


Now we can start building our model. We will start by creating two placeholders,
named tf_x and tf_y, and then build a Multilayer Artificial Neural Network from Scratch with three fully connected layers

We will use hyperbolic tangent activation functions (tanh) in the hidden layer, we will use the softmax function in the output layer

In [ ]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior() 
n_features = X_train_centered.shape[1]
n_classes = 10
random_seed = 123
np.random.seed(random_seed)
g = tf.Graph()
with g.as_default():
  #Creates the structure of the network
  tf.set_random_seed(random_seed)
  tf_x = tf.placeholder(dtype=tf.float32, shape=(None, n_features),name='tf_x')
  tf_y = tf.placeholder(dtype=tf.int32,shape=None, name='tf_y')
  # Generating one hot Tensor
  # is a Tensor in which all the values at indices where i =j and i!=j is same
  # one_hot method: This method accepts a Tensor of indices, a scalar defining depth of
  # the one hot dimension and returns a one hot Tensor with default on value 1 
  #and off value 0. These on and off values can be modified.
  y_onehot = tf.one_hot(indices=tf_y, depth=n_classes)
  h1 = tf.layers.dense(inputs=tf_x, units=50,activation=tf.tanh,name='layer1')
  h2 = tf.layers.dense(inputs=h1, units=50,activation=tf.tanh,name='layer2')
  logits = tf.layers.dense(inputs=h2, units=10, activation=None,name='layer3')
  predictions = {'classes' : tf.argmax(logits, axis=1,name='predicted_classes'),'probabilities' : tf.nn.softmax(logits,name='softmax_tensor')}

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:19: UserWarning: `tf.layers.dense` is deprecated and will be removed in a future version. Please use `tf.keras.layers.Dense` instead.
/usr/local/lib/python3.7/dist-packages/keras/legacy_tf_layers/core.py:255: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  return layer.apply(inputs)
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:20: UserWarning: `tf.layers.dense` is deprecated and will be removed in a future version. Please use `tf.keras.layers.Dense` instead.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: UserWarning: `tf.layers.dense` is deprecated and will be removed in a future version. Please use `tf.keras.layers.Dense` instead.


Next, we define the cost functions and add an operator for initializing the model variables as well as an optimization operator:

In [ ]:
## define cost function and optimizer:
with g.as_default():
  cost = tf.losses.softmax_cross_entropy(onehot_labels=y_onehot, logits=logits)
  optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.001)
  train_op = optimizer.minimize(loss=cost)
  init_op = tf.global_variables_initializer()

Before we start training the network, we need a way to generate batches of data. For this, we implement the following function that returns a generator:

In [ ]:
def create_batch_generator(X, y, batch_size=128, shuffle=False):
  X_copy = np.array(X)
  y_copy = np.array(y)
  if shuffle:
    data = np.column_stack((X_copy, y_copy))
    np.random.shuffle(data)
    X_copy = data[:, :-1]
    y_copy = data[:, -1].astype(int)

  for i in range(0, X.shape[0], batch_size):
    yield (X_copy[i:i+batch_size, :], y_copy[i:i+batch_size])

Next, we can create a new TensorFlow session, initialize all the variables in our network, and train it. We also display the average training loss after each epoch monitors the learning process later:


In [ ]:
## create a session to launch the graph
sess = tf.Session(graph=g)
## run the variable initialization operator
sess.run(init_op)

## 50 epochs of training:
for epoch in range(50):
  training_costs = []
  batch_generator = create_batch_generator(X_train_centered, y_train, batch_size=64)
  for batch_X, batch_y in batch_generator:
    ## prepare a dict to feed data to our network:
    feed = {tf_x:batch_X, tf_y:batch_y}
    batch_cost = sess.run([train_op, cost], feed_dict=feed)
    training_costs.append(batch_cost[1])
  #print(training_costs)
  mean_cost = float(np.mean(training_costs))
  epoch_to_print = int(epoch) + 1
  print(" -- Epoch %2d Avg. Training Loss: %.4f" % (epoch_to_print, mean_cost))


 -- Epoch  1 Avg. Training Loss: 1.5841
 -- Epoch  2 Avg. Training Loss: 0.9637
 -- Epoch  3 Avg. Training Loss: 0.7528
 -- Epoch  4 Avg. Training Loss: 0.6378
 -- Epoch  5 Avg. Training Loss: 0.5643
 -- Epoch  6 Avg. Training Loss: 0.5132
 -- Epoch  7 Avg. Training Loss: 0.4754
 -- Epoch  8 Avg. Training Loss: 0.4462
 -- Epoch  9 Avg. Training Loss: 0.4228
 -- Epoch 10 Avg. Training Loss: 0.4036
 -- Epoch 11 Avg. Training Loss: 0.3874
 -- Epoch 12 Avg. Training Loss: 0.3735
 -- Epoch 13 Avg. Training Loss: 0.3614
 -- Epoch 14 Avg. Training Loss: 0.3508
 -- Epoch 15 Avg. Training Loss: 0.3412
 -- Epoch 16 Avg. Training Loss: 0.3326
 -- Epoch 17 Avg. Training Loss: 0.3248
 -- Epoch 18 Avg. Training Loss: 0.3177
 -- Epoch 19 Avg. Training Loss: 0.3111
 -- Epoch 20 Avg. Training Loss: 0.3050
 -- Epoch 21 Avg. Training Loss: 0.2994
 -- Epoch 22 Avg. Training Loss: 0.2940
 -- Epoch 23 Avg. Training Loss: 0.2890
 -- Epoch 24 Avg. Training Loss: 0.2843
 -- Epoch 25 Avg. Training Loss: 0.2799


The training process may take a couple of minutes. Finally, we can use the trained model to do predictions on the test dataset:

In [ ]:
## do prediction on the test set:
feed = {tf_x : X_test_centered}
y_pred = sess.run(predictions['classes'],feed_dict=feed)
print('Test Accuracy: %.2f%%' % (100*np.sum(y_pred == y_test)/y_test.shape[0]))

Test Accuracy: 93.67%


We can see that by leveraging high-level APIs, we can quickly build a model and test it. Therefore, a high-level API is very useful for prototyping our ideas and quickly checking the results.